In [1]:
import pandas as pd

In [2]:
df = pd.read_json ('news_category_dataset.json',lines=True)
#df

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.shape

(124989, 6)

In [5]:
df.category.unique()

array(['CRIME', 'ENTERTAINMENT', 'WORLD NEWS', 'IMPACT', 'POLITICS',
       'WEIRD NEWS', 'BLACK VOICES', 'WOMEN', 'COMEDY', 'QUEER VOICES',
       'SPORTS', 'BUSINESS', 'TRAVEL', 'MEDIA', 'TECH', 'RELIGION',
       'SCIENCE', 'LATINO VOICES', 'EDUCATION', 'COLLEGE', 'PARENTS',
       'ARTS & CULTURE', 'STYLE', 'GREEN', 'TASTE', 'HEALTHY LIVING',
       'THE WORLDPOST', 'GOOD NEWS', 'WORLDPOST', 'FIFTY', 'ARTS'],
      dtype=object)

In [6]:
df.set_index('category',  inplace = True)
df

short_description  ...                                            authors
category                                                           ...                                                   
CRIME           She left her husband. He killed their children...  ...                                    Melissa Jeltsen
ENTERTAINMENT                            Of course it has a song.  ...                                      Andy McDonald
ENTERTAINMENT   The actor and his longtime girlfriend Anna Ebe...  ...                                         Ron Dicker
ENTERTAINMENT   The actor gives Dems an ass-kicking for not fi...  ...                                         Ron Dicker
ENTERTAINMENT   The "Dietland" actress said using the bags is ...  ...                                         Ron Dicker
...                                                           ...  ...                                                ...
WOMEN                                                              ...                                                   
TASTE           I often hear people describe cooking for one a...  ...         Food Riot, ContributorPlay with your food.
CRIME                                                              ...  Robert Siciliano, ContributorPersonal Security...
MEDIA                                                              ...                                     Katherine Fung
HEALTHY LIVING  Our thoughts and feelings are powerful, but ma...  ...  Mindy Utay, Contributor"Calming Life's Conflicts"

[124989 rows x 5 columns]

In [7]:
df.shape

(124989, 5)

In [8]:
df1 = df.loc[['BUSINESS','COMEDY','CRIME','SPORTS','RELIGION','POLITICS','HEALTHY LIVING']]

In [9]:
df1

short_description  ...                                            authors
category                                                           ...                                                   
BUSINESS        The investigation could lead to new U.S. tarif...  ...           David Shepardson and Jeff Mason, Reuters
BUSINESS        The new policy was unveiled weeks after the co...  ...                                Dominique Mosbergen
BUSINESS        Following the council vote, Amazon’s vice pres...  ...                           Gregory Scruggs, Reuters
BUSINESS        Victims will be free to go to court -- but a f...  ...                                         Emily Peck
BUSINESS        The breach is believed to have occurred betwee...  ...                                     Jenna Amatulli
...                                                           ...  ...                                                ...
HEALTHY LIVING  Instead of judging whether you made the right ...  ...  Elizabeth Grace Saunders, ContributorFounder, ...
HEALTHY LIVING  While there are strong arguments for the games...  ...         Mona Shattell, Contributornurse researcher
HEALTHY LIVING  My wake-up call marching orders were clear: No...  ...  Jane Shure, ContributorLeadership Coach, Psych...
HEALTHY LIVING  It is very difficult for some people to see an...  ...  Nancy Colier, ContributorPsychotherapist, inte...
HEALTHY LIVING  Our thoughts and feelings are powerful, but ma...  ...  Mindy Utay, Contributor"Calming Life's Conflicts"

[57274 rows x 5 columns]

In [10]:
df1.index.unique()

Index(['BUSINESS', 'COMEDY', 'CRIME', 'SPORTS', 'RELIGION', 'POLITICS',
       'HEALTHY LIVING'],
      dtype='object', name='category')

In [11]:
df2 = df1.reset_index()
df2

category  ...                                            authors
0            BUSINESS  ...           David Shepardson and Jeff Mason, Reuters
1            BUSINESS  ...                                Dominique Mosbergen
2            BUSINESS  ...                           Gregory Scruggs, Reuters
3            BUSINESS  ...                                         Emily Peck
4            BUSINESS  ...                                     Jenna Amatulli
...               ...  ...                                                ...
57269  HEALTHY LIVING  ...  Elizabeth Grace Saunders, ContributorFounder, ...
57270  HEALTHY LIVING  ...         Mona Shattell, Contributornurse researcher
57271  HEALTHY LIVING  ...  Jane Shure, ContributorLeadership Coach, Psych...
57272  HEALTHY LIVING  ...  Nancy Colier, ContributorPsychotherapist, inte...
57273  HEALTHY LIVING  ...  Mindy Utay, Contributor"Calming Life's Conflicts"

[57274 rows x 6 columns]

In [12]:
df2.category.unique()

array(['BUSINESS', 'COMEDY', 'CRIME', 'SPORTS', 'RELIGION', 'POLITICS',
       'HEALTHY LIVING'], dtype=object)

In [13]:
df2['category'].value_counts()

POLITICS          32739
HEALTHY LIVING     6694
BUSINESS           4254
SPORTS             4167
COMEDY             3971
CRIME              2893
RELIGION           2556
Name: category, dtype: int64

In [14]:
df3 = df2[["category","headline"]]
df3

category                                           headline
0            BUSINESS  U.S. Launches Auto Import Probe, China Vows To...
1            BUSINESS  Starbucks Says Anyone Can Now Sit In Its Cafes...
2            BUSINESS  Seattle Passes Controversial New Tax On City's...
3            BUSINESS  Uber Ends Forced Arbitration In Individual Cas...
4            BUSINESS  Chili's Hit By Data Breach, Credit And Debit C...
...               ...                                                ...
57269  HEALTHY LIVING  Why You Need Both a 'Bouncer' and a 'Bartender...
57270  HEALTHY LIVING  How Video Games Can Improve Dialogue on Mental...
57271  HEALTHY LIVING  Wake-Up Calls Inspired My Change From Overdriv...
57272  HEALTHY LIVING        Loving a Narcissist Without Losing Yourself
57273  HEALTHY LIVING                            Reasons Not to Be Happy

[57274 rows x 2 columns]

In [15]:
import string
df3['category']=df3.category.map({'BUSINESS':1,'COMEDY':2,'CRIME':3,'SPORTS':4,'RELIGION':5,'POLITICS':6,'HEALTHY LIVING':7})
df3['headline'] = df3.headline.map(
    lambda x: x.lower().translate(str.maketrans('','', string.punctuation))
)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [16]:
df3


category                                           headline
0             1  us launches auto import probe china vows to de...
1             1  starbucks says anyone can now sit in its cafes...
2             1  seattle passes controversial new tax on citys ...
3             1  uber ends forced arbitration in individual cas...
4             1  chilis hit by data breach credit and debit car...
...         ...                                                ...
57269         7  why you need both a bouncer and a bartender to...
57270         7  how video games can improve dialogue on mental...
57271         7  wakeup calls inspired my change from overdrive...
57272         7        loving a narcissist without losing yourself
57273         7                            reasons not to be happy

[57274 rows x 2 columns]

In [17]:
X=[]
Y=[]
X=df3.iloc[:,1].values
Y=df3.iloc[:,0].values

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, 
    Y,test_size=0.15, 
    random_state = 0
)


In [19]:
X_train
X_train.shape

(48682,)

In [20]:
for i in range(1,5):
    print(X_train[i])


jeb bush rewrites the history of the iraq war
anthony scaramucci prompts search of scaramouch and people cant handle the definition
jeb bush was not shy about using his white house connections
huffpost hill  media to cover donald trump speech


In [21]:
# A list of common english words which should not affect predictions
# manually entering stopwords or we can also use library like nltk
stopwords = ['a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'all', 'almost', 'alone',
             'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'amoungst', 'amount',
             'an', 'and', 'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'around',
             'as', 'at', 'back', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before',
             'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'between', 'beyond', 'bill', 'both',
             'bottom', 'but', 'by', 'call', 'can', 'cannot', 'cant', 'co', 'con', 'could', 'couldnt', 'cry', 'de',
             'describe', 'detail', 'did', 'do', 'does', 'doing', 'don', 'done', 'down', 'due', 'during', 'each', 'eg',
             'eight', 'either', 'eleven', 'else', 'elsewhere', 'empty', 'enough', 'etc', 'even', 'ever', 'every', 'everyone',
             'everything', 'everywhere', 'except', 'few', 'fifteen', 'fify', 'fill', 'find', 'fire', 'first', 'five', 'for',
             'former', 'formerly', 'forty', 'found', 'four', 'from', 'front', 'full', 'further', 'get', 'give', 'go', 'had',
             'has', 'hasnt', 'have', 'having', 'he', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', 'hereupon',
             'hers', 'herself', 'him', 'himself', 'his', 'how', 'however', 'hundred', 'i', 'ie', 'if', 'in', 'inc', 'indeed',
             'interest', 'into', 'is', 'it', 'its', 'itself', 'just', 'keep', 'last', 'latter', 'latterly', 'least', 'less',
             'ltd', 'made', 'many', 'may', 'me', 'meanwhile', 'might', 'mill', 'mine', 'more', 'moreover', 'most', 'mostly',
             'move', 'much', 'must', 'my', 'myself', 'name', 'namely', 'neither', 'never', 'nevertheless', 'next', 'nine',
             'no', 'nobody', 'none', 'noone', 'nor', 'not', 'nothing', 'now', 'nowhere', 'of', 'off', 'often', 'on', 'once',
             'one', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'our', 'ours', 'ourselves', 'out', 'over', 'own',
             'part', 'per', 'perhaps', 'please', 'put', 'rather', 're', 's', 'same', 'see', 'seem', 'seemed', 'seeming',
             'seems', 'serious', 'several', 'she', 'should', 'show', 'side', 'since', 'sincere', 'six', 'sixty', 'so', 
             'some', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhere', 'still', 'such', 'system',
             't', 'take', 'ten', 'than', 'that', 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'thence', 'there',
             'thereafter', 'thereby', 'therefore', 'therein', 'thereupon', 'these', 'they', 'thickv', 'thin', 'third', 'this',
             'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'to', 'together', 'too', 'top', 'toward',
             'towards', 'twelve', 'twenty', 'two', 'un', 'under', 'until', 'up', 'upon', 'us', 'very', 'via', 'was', 'we',
             'well', 'were', 'what', 'whatever', 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby',
             'wherein', 'whereupon', 'wherever', 'whether', 'which', 'while', 'whither', 'who', 'whoever', 'whole', 'whom',
             'whose', 'why', 'will', 'with', 'within', 'without', 'would', 'yet', 'you', 'your', 'yours', 'yourself',
             'yourselves']

In [22]:
len(stopwords)

327

In [23]:
vocab = {}
for i in range(len(X_train)):
    word_list = []
    for word in X_train[i].split():
        word_new  = word.strip()
        if (len(word_new)>2)  and (word_new not in stopwords):  
            if word_new in vocab:
                vocab[word_new]+=1
            else:
                vocab[word_new]=1
                
vocab

{'trevor': 143,
 'noah': 142,
 'donald': 3110,
 'trump': 6460,
 'making': 200,
 'bank': 76,
 'president': 677,
 'jeb': 182,
 'bush': 252,
 'rewrites': 2,
 'history': 212,
 'iraq': 99,
 'war': 379,
 'anthony': 60,
 'scaramucci': 26,
 'prompts': 14,
 'search': 57,
 'scaramouch': 1,
 'people': 797,
 'handle': 35,
 'definition': 8,
 'shy': 9,
 'using': 126,
 'white': 878,
 'house': 1094,
 'connections': 14,
 'huffpost': 411,
 'hill': 214,
 'media': 198,
 'cover': 44,
 'speech': 246,
 'espn': 34,
 'pulls': 44,
 'broadcaster': 2,
 'virginia': 125,
 'game': 252,
 'robert': 81,
 'lee': 29,
 'week': 222,
 'cheese': 10,
 'curt': 13,
 'schilling': 13,
 'threatens': 72,
 'run': 242,
 '2024': 8,
 'criticism': 53,
 'benjamin': 3,
 'netanyahu': 33,
 'defends': 122,
 'planned': 169,
 'congress': 459,
 'feds': 76,
 'investigating': 33,
 'exxon': 32,
 'climate': 430,
 'change': 470,
 'nebraska': 17,
 'senator': 223,
 'uses': 81,
 'gore': 18,
 'porn': 29,
 'argue': 10,
 'restoring': 13,
 'death': 417,
 '

In [26]:
len(vocab)
num_words = [0 for i in range(max(vocab.values())+1)] 
freq = [i for i in range(max(vocab.values())+1)] 
for key in vocab:
    num_words[vocab[key]]+=1

In [27]:
cutoff_freq = 2
num_words_above_cutoff = len(vocab)-sum(num_words[0:cutoff_freq]) 
print("Number of words with frequency higher than cutoff frequency({}) :".format(cutoff_freq),num_words_above_cutoff)

Number of words with frequency higher than cutoff frequency(2) : 15754


In [28]:
features = []
for key in vocab:
    if vocab[key] >=cutoff_freq:
        features.append(key)

In [31]:
len(features)
import numpy as np

In [32]:
# To represent training data as word vector counts
X_train_dataset = np.zeros((len(X_train),len(features)))
# This can take some time to complete
for i in range(len(X_train)):
    #print(i) # Uncomment to see progress
    word_list = [ word.strip() for word in X_train[i].split()]
    for word in word_list:
        if word in features:
            X_train_dataset[i][features.index(word)] += 1

In [33]:
# To represent test data as word vector counts
X_test_dataset = np.zeros((len(X_test),len(features)))
# This can take some time to complete
for i in range(len(X_test)):
    # print(i) # Uncomment to see progress
    word_list = [ word.strip() for word in X_test[i].split()]
    for word in word_list:
        if word in features:
            X_test_dataset[i][features.index(word)] += 1

In [34]:
import os
import string
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.naive_bayes import MultinomialNB


In [35]:
# Implementing Multinomial Naive Bayes from scratch
class MultinomialNaiveBayes:
    
    def __init__(self):
        # count is a dictionary which stores several dictionaries corresponding to each news category
        # each value in the subdictionary represents the freq of the key corresponding to that news category 
        self.count = {}
        # classes represents the different news categories
        self.classes = None
    
    def fit(self,X_train,Y_train):
        # This can take some time to complete       
        self.classes = set(Y_train)
        for class_ in self.classes:
            self.count[class_] = {}
            for i in range(len(X_train[0])):
                self.count[class_][i] = 0
            self.count[class_]['total'] = 0
            self.count[class_]['total_points'] = 0
        self.count['total_points'] = len(X_train)
        
        for i in range(len(X_train)):
            for j in range(len(X_train[0])):
                self.count[Y_train[i]][j]+=X_train[i][j]
                self.count[Y_train[i]]['total']+=X_train[i][j]
            self.count[Y_train[i]]['total_points']+=1
    
    def __probability(self,test_point,class_):
        
        log_prob = np.log(self.count[class_]['total_points']) - np.log(self.count['total_points'])
        total_words = len(test_point)
        for i in range(len(test_point)):
            current_word_prob = test_point[i]*(np.log(self.count[class_][i]+1)-np.log(self.count[class_]['total']+total_words))
            log_prob += current_word_prob
        
        return log_prob
    
    
    def __predictSinglePoint(self,test_point):
        
        best_class = None
        best_prob = None
        first_run = True
        
        for class_ in self.classes:
            log_probability_current_class = self.__probability(test_point,class_)
            if (first_run) or (log_probability_current_class > best_prob) :
                best_class = class_
                best_prob = log_probability_current_class
                first_run = False
                
        return best_class
        
  
    def predict(self,X_test):
        # This can take some time to complete
        Y_pred = [] 
        for i in range(len(X_test)):
        # print(i) # Uncomment to see progress
            Y_pred.append( self.__predictSinglePoint(X_test[i]) )
        
        return Y_pred
    
    def score(self,Y_pred,Y_true):
        # returns the mean accuracy
        count = 0
        for i in range(len(Y_pred)):
            if Y_pred[i] == Y_true[i]:
                count+=1
        return count/len(Y_pred)

In [38]:
import time
from sklearn.metrics import classification_report, confusion_matrix
clf2 = MultinomialNaiveBayes()
start_time=time.time()
clf2.fit(X_train_dataset,Y_train)
time_to_train=time.time()-start_time
print("Time taken for training: "+str(time_to_train)+" seconds")
print(" ")
Y_test_pred = clf2.predict(X_test_dataset)
our_score_test = clf2.score(Y_test_pred,Y_test)  
print("Overall accuracy score of model :",our_score_test)
print(" ")
print("category wise accuracy score and classification report ")
print(classification_report(Y_test, Y_test_pred))
print(" ")
print("----------confusion matrix for classification----------")
print(" ")
print(confusion_matrix(Y_test, Y_test_pred))

Time taken for training: 1602.1095197200775 seconds
 
Overall accuracy score of model : 0.8026070763500931
 
category wise accuracy score and classification report 
              precision    recall  f1-score   support

           1       0.66      0.46      0.54       643
           2       0.70      0.55      0.62       584
           3       0.70      0.78      0.74       418
           4       0.81      0.78      0.80       619
           5       0.75      0.49      0.59       383
           6       0.85      0.92      0.88      4937
           7       0.73      0.75      0.74      1008

    accuracy                           0.80      8592
   macro avg       0.74      0.67      0.70      8592
weighted avg       0.80      0.80      0.80      8592

 
----------confusion matrix for classification----------
 
[[ 294    8    8   15    4  209  105]
 [  12  324    7   24    9  168   40]
 [   4    4  326   10    3   61   10]
 [   5   16   18  483    5   69   23]
 [   9   13    9    5  186